### ISSUE TITLE
[FR] - handle multiple qlik licenses

### ISSUE THREAD

**Issue by r-hannuschka** [senseexcel/ser-web-management#100]
In case a user has multiple sense excel reporting licenses, the user should select which sense excel reporting license would be taken.

@konne how we want to save the license to server ? 

Currently there could be only one license file in contentlib/senseexcel named license.txt but if we got multiple licenses we need to save them.

Should we use multiple files license_0.txt and license_1.txt ( maybe custom name format ) or write it all into one file with specific seperator to determine here starts a new license ?

**Comment by konne** [comment]
@r-hannuschka we save only one. If the server give a result of multiple EXCEL Licences, the QMC should just open an Dialog and give the user the possibility to pick one.

**Comment by r-hannuschka** [comment]
filtering all received licenses from web service for EXCEL_ prefix. Which one which has that prefix will be taken. If more Licenses exists (should not really happen) with that token only the first will taken.
