### ISSUE TITLE
[FR] - delete generated reports in hub

### ISSUE THREAD

**Issue by r-hannuschka** [senseexcel/ser-web-management#116]
Since it is not possible to delete generated reports into hub, we could implement a custom section to show and delete generated reports.

@konne @AlexanderGoerlich @mossbeard we should talk about that possible feature.

**Comment by konne** [comment]
👍 this also have a real good advertis effect, because all NPrinting users miss that feature and they can install our QMC to fix that.
@AlexanderGoerlich please let us plan this next monday

**Comment by r-hannuschka** [comment]
Solved and implemented currently in development.
