### ISSUE TITLE
[FR] Licensemanager - Tokens

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#157]

**Comment by AlexanderGoerlich** [comment]
Please add Sense Excel license "Excel_Token"!
![image](https://user-images.githubusercontent.com/13659581/53640560-c56d1a00-3c2c-11e9-81ea-1a0df40d9f85.png)

**Comment by r-hannuschka** [comment]
Since we only support User Licenses we need to update Licensemanager to handle Token Licenses to avoid License Validation Error.
