### ISSUE TITLE
[BUG] Layout misrepresentation license

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#231]

**Comment by AlexanderGoerlich** [comment]
![layout_Error_SMC](https://user-images.githubusercontent.com/13659581/55607197-d81ec580-577b-11e9-9f7c-d601b0a1e162.png)

**Comment by r-hannuschka** [comment]
@AlexanderGoerlich can u add a description what is the bug ? 

I think it is the text flows out of the container, but the message seems to be correct since we dont handle neither a user license nor token license, so this is unknown for the smc and that will be displayed.
