### ISSUE TITLE
[FR] new interface for ContentLib template selektion

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#267]

**Comment by AlexanderGoerlich** [comment]
Please add a button and show a modal window like this:

![image](https://user-images.githubusercontent.com/13659581/59601053-37e20700-9103-11e9-999b-d380d88ef737.png)

**Comment by AlexanderGoerlich** [comment]
remove "template output format" input field 

![image](https://user-images.githubusercontent.com/13659581/59601139-74adfe00-9103-11e9-8414-d531db4721da.png)

**Comment by AlexanderGoerlich** [comment]
- [ ] create new modal for "Template"
- [ ] add a new buton "seletc template"
- [ ] remove input "template output format"
- [ ] add new checkbox for "template output Password"

**Comment by r-hannuschka** [comment]
Duplicate of #148
