### ISSUE TITLE
[BUG] after template uploading the file is corrupted

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#285]
All files are corrupted! 
If we upload the templates manual by qmc uploader all works fine!!!

![image](https://user-images.githubusercontent.com/13659581/60668482-61719100-9e6c-11e9-8ad8-731e28368d62.png)

**Comment by r-hannuschka** [comment]
This issue seems to be caused by QRS needs as Body the file data ( blob ) Fileupload module sends FormData with Blob.

This should fixed in file upload module it should send plain file instead of FormData.

@see https://github.com/r-hannuschka/ngx-fileupload/issues/14

**Comment by r-hannuschka** [comment]
Solved with ngx-fileupload version 0.5.0 ( currently implemented in beta 0.5.0-beta.1 ) install with npm i --save @r-hannuschka/ngx-fileupload@beta
