### ISSUE TITLE
[FR] add parameter to default

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#291]
please insert the following paramert to the default settings, at this point you have to manualy insert it 

connections: @CONFIGCONNECTION@

Example:
file:
        {
                  active: true
                  target: lib://SERReports
                  mode: DELETEALLFIRST
                  connections: @CONFIGCONNECTION@
        }
hub:
        {
                  active: true
                  mode: DELETEALLFIRST
                  #owner: test
                  connections: @CONFIGCONNECTION@
        }

**Comment by r-hannuschka** [comment]
duplicate of #289
