### ISSUE TITLE
[FR] multiple reports / wizard

### ISSUE THREAD

**Issue by r-hannuschka** [senseexcel/ser-web-management#310]
Since we only support to handle one report but SER could handle multiple reports we needs to support multiple Reports. This should be solved with a new  view which shows all Reports in an App.

## Report Overview

- [ ] display report overview as tile 
- [ ] clone report ( create new one with data from report which has been cloned )
- [ ] edit report ( current edit form )
- [ ] delete report

* clone report: by default SER supports tags like @PROPERTY@ to reference to previous report and get data from this one, for the first step we will ignore that to keep things  simple. If we clone a report we clone this one completly with all data wich is in report.

## Report Create ( Wizard )

multiple steps to create a new report after app has been created

- [ ] step line multiple steps
- [ ] Step1: show overview what to create ( 1 Report to Multiple Users / 1 User with multiple Reports create one report and clone this one multiple times)
- [ ] Step2: select existing App
- [ ] Step3: select template ( upload sense excel reporting template )
- [ ] step4: output

**Comment by thomashaenig** [comment]
closed
