### ISSUE TITLE
[FR] add and change license user   directly by adding a customer proberty

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#344]
Its just an idea to add license to users:

![image](https://user-images.githubusercontent.com/13659581/64535622-e7e89a00-d317-11e9-8fc5-84237e108c5d.png)

in the qmc can be :

![image](https://user-images.githubusercontent.com/13659581/64535771-267e5480-d318-11e9-9d36-f6b43256451a.png)

**Comment by thomashaenig** [comment]
moved to new repository
