### ISSUE TITLE
updating the license will remove all users which were already entered

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#346]
when loading license from server, include a popover with the question update or load new license. when load new license use same logic like now, when updat merge new license from Server with existing license in SMC (user part of the license), so the already entered users in the smc will remaine

**Comment by r-hannuschka** [comment]
I think we should only merge this one if this is the same license type, if we get a complete different license type like Token License and User License merging would be different.

**Comment by r-hannuschka** [comment]
Solved, currently we will only merge a user license ( loaded from server ) if currently a user license exists on system.

That means if you have a user license and now get a token license, the user license will completly replaced, if u have a user license and load a new user license, all users will merged from existing license to new user license.

License Headers will completly replaced ( you dont have to touch them).
