### ISSUE TITLE
enter application name and id 

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#347]
example:
Executive Dashboard Report (37483-27384-...)

![image](https://user-images.githubusercontent.com/17725886/65689466-7033a280-e06d-11e9-899f-cb9401186e66.png)

check that the own app can not be selected

**Comment by r-hannuschka** [comment]
- [ ] fetch app from qmc to get all informations
- [ ] display app name / app id in search results since app name can exists multiple times

@blocked by #365 since we need to fetch app first (by id) to get all informations we need to show name, ID
