### ISSUE TITLE
single quotes missing in arrays for selections

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#354]
when population the hjson, the values for the arrays should be enclodes in singel quots

**Comment by r-hannuschka** [comment]
We have tested this now, this is not a Problem in SMC or Configuration. This is more a problem in PDF Generation.

Steps to Reproduce:

Step 1:
Set a filter for Region and Select only Europe:
Title: Europe
Value is 2.004.196 

Step 2:
Set a filter for Region Middle East (not anything else)
Title: Middle East
Value: dont know but all data are in here

Step 3:
Set a filter for Region [Europe, Americas]
Title Americas / Europe ( in **one** line)
Value has changed now (both are in there) but title has been sorted

Step 4 (combine Europe and Middle East):
Set a filter for Region [Middle East, Europe]
Title Europe (middle east seems to be missing here)
Value: Diffrent from **only europe** 

What happens is simple, data will correctly rendered into template just the title is wrong. In Short Europe and Middle East dont fits on **one** line so middle east go to next line and we dont see it anymore. But all Data from Middle Easte are in.

**Comment by thomashaenig** [comment]
@AlexanderGoerlich the test was succussfully and the hjson gets created corect from smc. In you test case it did not work because the template has a sheetloop included, which eliminates the set selection.

This issue will be closed
