### ISSUE TITLE
inside the report section show the app name in top of the side and maybe edit it

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#361]

**Comment by thomashaenig** [comment]
![image](https://user-images.githubusercontent.com/17725886/65687896-69576080-e06a-11e9-805e-6b35661d89d6.png)

**Comment by r-hannuschka** [comment]
Only show the name, we will append edit feature as inline edit in table view directly or find any other solution for that. 

I dont like the idea of inline edit in reporting jobs header.
