### ISSUE TITLE
think about naming (reporting app; relevant app, reporting job/task)

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#362]
![image](https://user-images.githubusercontent.com/13659581/66997297-78ae5480-f0d2-11e9-9354-62c4a1c749ce.png)

**Comment by thomashaenig** [comment]
@AlexanderGoerlich please review with lance the naming and add list to this issue

**Comment by r-hannuschka** [comment]
Topbar Breadcrumb menu could not renamed to Reporting App Name > Jobs since every breadcrumb is one anchor point to an page. So i could not split 1 Route into 2 Routes.
