### ISSUE TITLE
Display Data-Connection where Tag = SER

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#366]

**Comment by AlexanderGoerlich** [comment]
when editing a distribution field in SMC then show only all data-connections like the templates selection. Users can see ony by "SER" tag and this select **"lib://SER_Output"**. the input field are allways disabled. No dynamics are required!


![image](https://user-images.githubusercontent.com/13659581/65877387-d7ae6280-e38b-11e9-8305-7abfa2eb9be8.png)

**Comment by thomashaenig** [comment]
@r-hannuschka plz check comment

**Comment by thomashaenig** [comment]
@r-hannuschka plz change of show by first char
