### ISSUE TITLE
change result view

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#371]
When is possible: please change the result view! May be like a accordion view like the TaskId look and feel. 

Some clients have very loong loops :-) 

![image](https://user-images.githubusercontent.com/13659581/66994558-bc528f80-f0cd-11e9-912b-5243c7dd6abb.png)

![image](https://user-images.githubusercontent.com/13659581/66994536-b2c92780-f0cd-11e9-9c69-8d475faec020.png)

**Comment by r-hannuschka** [comment]
Can i get a example response for this since i could not get that much information from ser.

Simply the full string in last line: 

Results: ....

**Comment by AlexanderGoerlich** [comment]
Results: hubResults\: \r\n  \fileResults\: \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_90.pdf does not exist.\\r\n\reportName\: \Report_Seller_90r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_100.pdf does not exist.\\r\n\reportName\: \Report_Seller_100r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35641213.pdf does not exist.\\r\n\reportName\: \Report_Seller_35641213r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35640592.pdf does not exist.\\r\n\reportName\: \Report_Seller_35640592r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642458.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642458r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642462.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642462r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642464.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642464r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642466.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642466r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642468.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642468r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642470.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642470r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642472.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642472r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642475.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642475r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642480.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642480r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642482.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642482r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642492.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642492r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642493.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642493r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642495.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642495r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642497.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642497r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642502.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642502r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642504.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642504r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642506.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642506r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642509.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642509r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642510.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642510r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642512.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642512r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642514.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642514r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642515.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642515r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642519.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642519r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642521.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642521r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642523.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642523r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642525.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642525r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642528.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642528r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642529.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642529r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642534.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642534r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642539.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642539r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642541.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642541r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642544.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642544r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642546.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642546r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642551.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642551r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642553.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642553r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642556.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642556r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642560.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642560r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642565.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642565r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642558.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642558r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642567.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642567r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642568.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642568r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642570.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642570r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642574.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642574r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642576.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642576r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642578.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642578r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642580.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642580r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642594.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642594r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642600.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642600r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642608.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642608r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642606.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642606r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642611.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642611r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642613.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642613r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642588.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642588r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642620.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642620r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642617.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642617r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642623.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642623r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642626.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642626r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642632.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642632r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642629.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642629r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642635.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642635r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642641.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642641r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642638.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642638r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642644.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642644r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642646.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642646r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642651.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642651r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642654.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642654r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642660.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642660r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642657.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642657r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642662.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642662r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642665.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642665r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642676.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642676r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642678.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642678r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642674.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642674r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642688.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642688r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642698.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642698r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642668.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642668r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642700.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642700r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642705.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642705r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642711.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642711r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642713.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642713r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642708.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642708r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642718.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642718r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642728.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642728r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642733.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642733r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642749.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642749r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642781.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642781r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642766.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642766r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35642792.pdf does not exist.\\r\n\reportName\: \Report_Seller_35642792r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35643733.pdf does not exist.\\r\n\reportName\: \Report_Seller_35643733r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_35643736.pdf does not exist.\\r\n\reportName\: \Report_Seller_35643736r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304557.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304557r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304560.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304560r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304562.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304562r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304565.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304565r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304574.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304574r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304578.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304578r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304580.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304580r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304587.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304587r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304590.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304590r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304592.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304592r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304594.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304594r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304596.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304596r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304599.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304599r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304613.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304613r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304615.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304615r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304617.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304617r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304621.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304621r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304623.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304623r\n    \r\n    \r\n\success\: false\r\n\message\: \The file D:MyReportsReport_Seller_36304625.pdf does not exist.\\r\n\reportName\: \Report_Seller_36304625r\n    \r\n  \r\n  \mailResults\: \r\n

**Comment by r-hannuschka** [comment]
Thx alot, but i think we have to go another way, by default a JSON would be send but qlik seems to convert this one into this. And we could not parse this correctly or easy.

.\r\n\reportName: \Report_Seller_36304594r\n

this is a core problem, if we look on \r\n\reportname the result will be eportName because the \r is a linebreak.
