### ISSUE TITLE
hide or disabled the rest of SER settings when app is not connected

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#372]
Please change for better workflow!

When I am inside of a settings some the connection will be lost after some minutes... the user do not understand why can he not see e.g. the values from the "SELECTIONS" not can use or see. So we know that ... we have to re-connect the the app. If you have a better idea or solutions let me know that :-) 

![image](https://user-images.githubusercontent.com/13659581/66996117-6d5a2980-f0d0-11e9-9a1d-9600f5b14913.png)

**Comment by r-hannuschka** [comment]
All these fields are free input fields so you can enter what u want. If you connected to an app then you have also a autocompletion which helps you to find fields / dimensions.

If i want add a new filter ( i know all data ) so i dont have to connect to an app just to set an filter. Disable this would mean i also have to connect to an app first before i can do anything. Or maybe the fields / dimensions not exists in the moment but added later by other people.

The downside here is, you dont know is what i entering correct ?

**Comment by AlexanderGoerlich** [comment]
Ok, I understand! 
But we have to be sure ... if app is not conntected then I never will see all possibles filters!
Any ideas ... or workflow for that? Like "I am currentlich disconnected to this app" you dont will see any autocomplete filters or once of that.

**Comment by r-hannuschka** [comment]
Maybe like Qlik does, add more menu items on right side and enable / disable views just as simple as that. But then we have to refactor menu behavior ( scroll to ) into show/hide view.

Or we could try something like a Accordion, all menu items are collpased at start and could be opened.

Downside could be you get much white space, Accordeon not that much like enable / disable section.

Maybe just refactoring full Report Page, i know this is a big form and i'm not a designer and that is what we need a designer wo knows how to solve this.

Greetings Ralf

**Comment by thomashaenig** [comment]
will be closed, because all Settings should be visible even when not connected to application
