### ISSUE TITLE
[FR] Support multiple Selections

### ISSUE THREAD

**Issue by r-hannuschka** [senseexcel/ser-web-management#61]
Add behavior to support multiple selections

**Comment by r-hannuschka** [comment]
@konne 

We dont talk about that really:

I mean with multiple Selections the same as in Qlik ( Select multiple Items in a List ) so we could open multiple apps / taks and edit them in queue.  

If we should implement this, i want to talk about how this should be implemented. In Qlik it is we edit multiple apps and add the same value ( Tag, Task ) on every app which has been opened. That seems not very useful for me, since we edit an script in a report app.

**Comment by konne** [comment]
@r-hannuschka I think this is a missunderstanding. I see here only one qlik app and just multiple selection in this app. Please let us look tomorrow on that issue

**Comment by r-hannuschka** [comment]
Yep i thought u would mean multiple selections :) That ticket was opened from me as i have implement multiple selections on shared content, so we could select and delete multiple items at once. 

After that i think i could implement the same for all other lists, i mean why not we could open another app for editing after we saved the first one, like a queue. 

Multiple Template Selections will handled here: #147

**Comment by thomashaenig** [comment]
multiselect is included, issue will be closed
