### ISSUE TITLE
[FR] send SER script from wizard  to support per email

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#67]
If the user have a problem ... send a support mail with the current SER script

**Comment by AlexanderGoerlich** [comment]
@r-hannuschka : please use same process like Sense Excel Support [serial]@support.qlik2go.net" with a body Ser-Task Script

**Comment by thomashaenig** [comment]
@AlexanderGoerlich this should be excluded from smc, should be discussed to develop new tool, which collects all informations (logs, skript, ...)

**Comment by thomashaenig** [comment]
net required anymore
