### ISSUE TITLE
don't forget to update URL from https://support.qlik2go.net TO https://license.senseexcel.com

### ISSUE THREAD

**Issue by r-hannuschka** [senseexcel/ser-web-management#98]

**Comment by r-hannuschka** [comment]
@AlexanderGoerlich

![image](https://user-images.githubusercontent.com/25415574/48765088-b8e23880-ecb1-11e8-8b45-81f3e74b72d4.png)

Request is not working against https://license.senseexcel.com with response (failed)

complete request looks like this: 

https://license.senseexcel.com/lefupdate/update_lef.json?serial=><QLIK_SERIAL_NUMBER>&chk=<CHECKSUM>&callback=ng_jsonp_callback_0

Anyway u can just enter what u want for qlik serial or checksum, the backend should throw an error after that, but currently the request just failed.

**Comment by konne** [comment]
@r-hannuschka I have to solve the https issue, please ask Florian for the other issue

**Comment by r-hannuschka** [comment]
Florian works correctly, okay with old url i can get data for my request.  

I mean for testing u can enter what u want for Qlik License Key / Checksum ( dont care or enter a valid qlik license / checksum but not my :P ) because it is just a test to see the requests receives the Backend. And if u get then an error for serial=foobar&checksum=123 this is all okay, but u can see request passes through. 

Rest API in general is working now nothing to do at the moment, tested with old url.

**Comment by konne** [comment]
@r-hannuschka please check, new ssl certificate is set and valid

**Comment by r-hannuschka** [comment]
working great
